services:
  - type: web
    name: frappemcp
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: ERPNEXT_URL
        value: "https://erp.ravanaindustries.com"
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
